service: rollin-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2

plugins:
  - serverless-offline
functions:
  app:
    handler: dist/main.handler
    events:
      - httpApi: '*'
